use_frameworks!

platform :ios, '10.0'

target 'MKBeaconXProACTag_Example' do
  pod 'MKBeaconXProACTag', :path => '../'

  target 'MKBeaconXProACTag_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
